### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (5504,) (5632,) (5504,) 

### ISSUE THREAD

**Issue by chelovek12565** [unixpickle/udt-voice-swap#2]
Whenever I tried to apply mapping current error is raising. What is the solution?
![image](https://user-images.githubusercontent.com/80477441/156937049-ee80eacd-ad78-452f-8d40-fd3a767a4db2.png)

**Comment by chelovek12565** [comment]
ok, I just changed .wav format to .mp3 format

**Comment by unixpickle** [comment]
Glad you got it working!
